### ISSUE TITLE
Error on php 7.0.4 Argument 1 passed to October\Rain\Foundation\Exception\Handler::report() must be an instance of Exception, instance of Error given

### ISSUE THREAD

**Issue by netandreus** [scottbedard/oc-debugbar-plugin#12]
On php 7 when activating plugin got an error on homepage.

Uncaught TypeError: Argument 1 passed to October\Rain\Foundation\Exception\Handler::report() must be an instance of Exception, instance of Error given, called in /html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 73 and defined in /html/vendor/october/rain/src/Foundation/Exception/Handler.php:42 Stack trace: #0 /html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(73): October\Rain\Foundation\Exception\Handler->report(Object(Error)) #1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error)) #2 {main} thrown

/html/vendor/october/rain/src/Foundation/Exception/Handler.php line 42

TYPE

Undefined

EXCEPTION

Symfony\Component\Debug\Exception\FatalErrorException

```
 *
 * This is a great spot to send exceptions to Sentry, Bugsnag, etc.
 *
 * @param  \Exception  $e
 * @return void
 */
public function report(Exception $exception)
{
    if ($this->shouldntReport($exception))
        return;

    Log::error($exception);
}
```

**Comment by bitclaw** [comment]
@netandreus This issue can be closed since this is related to another issue: https://github.com/octobercms/october/issues/1636
