### ISSUE TITLE
Debugbar appears on all backend and frontend pages

### ISSUE THREAD

**Issue by Cellular-** [scottbedard/oc-debugbar-plugin#14]
The debugbar is appearing on all backend and frontend pages regardless if you're a signed in user, signed in admin or guest introducing a huge security flaw.

It should only appear on backend pages with an admin signed in.

October build 361
Browser Google Chrome

**Comment by eXpl0it3r** [comment]
While limiting the scope makes totally sense, you shouldn't be running your site in debug mode on production. :wink:

**Comment by scottbedard** [comment]
Closing, this is desired behavior. To hide the debug bar you'll need to take your site out of debug mode. See #27 and #29
