### ISSUE TITLE
After install plugin

### ISSUE THREAD

**Issue by tim0991** [scottbedard/oc-debugbar-plugin#18]
I install plugin by command line
```php
php artisan plugin:install bedard.debugbar
```

And i got the following error
> PHP Fatal error:  Class Illuminate\Cache\FileStore contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Cache\Store::many, Illuminate\Contracts\Cache\Store::putMany) in /Users/HFY/www/october/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php on line 250
PHP Fatal error:  Cannot instantiate abstract class Illuminate\Cache\FileStore in /Users/HFY/www/october/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php on line 151

After i delete vendor of plugin directory, it works , [so i hope it can be installed by composer](https://github.com/scottbedard/oc-debugbar-plugin/pull/17)

**Comment by scottbedard** [comment]
Solved by #17
