### ISSUE TITLE
Cannot create Users while Debugbar is enabled

### ISSUE THREAD

**Issue by kealsera** [scottbedard/oc-debugbar-plugin#19]
I am currently not able to create a new users while debugbar is enabled - same is true for several other functions in backend. A Fresh new installation of octobercms even failed after attaching project id (and downloading debugbar) to a similar error.

PHP Version	5.6.30 & October Build 419

![image](https://user-images.githubusercontent.com/10854875/26897978-acc56b0a-4bca-11e7-9a8b-81bdb32c846a.png)

**Comment by fdeneux** [comment]
+1 since I updated October to Build 419

```
Cannot add AuthCollector to Laravel Debugbar: Class auth does not exist
=> Exception in /vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#429

Class auth does not exist
=> ReflectionException in /vendor/laravel/framework/src/Illuminate/Container/Container.php#741
```

Or is this a **barryvdh/laravel-debugbar** issue?

**Comment by keiosweb** [comment]
+1 to Kealsera issue at 419, saving in backend stopped working with Debugbar enabled. 

Edit: Actually try to install it manually with git clone - issue is fixed with barryvdh/laravel-debugbar 2.4.x , seems like in October Market there is still old version.

**Comment by scottbedard** [comment]
@fdeneux The latest release was an upgrade for build 420, there should have been a prompt when upgrading asking you to confirm. Try upgrading your October instance, and see if the problem persists.

**Comment by fdeneux** [comment]
@scottbedard fixed now, thank you.
