### ISSUE TITLE
Specify strict dependency for illuminate/support

### ISSUE THREAD

**Issue by keiosweb** [scottbedard/oc-debugbar-plugin#2]
Hi Scott,

Your plugin requires Barry's debugbar, which in turn has an unbound dependency on illuminate/support and ends up pulling illuminate/support 5.1. Since Otwell doesn't really care about semver 5.1 Collection is incompatible with 5.0 Collection, thus ends up crashing everything. Therefore please add explicit dependency in your composer.json to use:

```
"illuminate/support": "5.0.*",
```

since this is version OctoberCMS is locked into.

Cheers.

**Comment by Tantacula** [comment]
Actual October CMS version works on laravel 5.1, so this plugin requires
`"illuminate/support": "5.1.*",` instead 5.0 or 5.4

**Comment by schneider-simon** [comment]
+1 :+1:

**Comment by LukeTowers** [comment]
This should no longer be a problem assuming you are not running composer update or install from within the plugin folder itself. Either get the plugin from the marketplace where these conflicts will be resolved for you or pull in its dependencies from your project root composer.json where the conflicts will also be dealt with properly.
