### ISSUE TITLE
debugbar code appended to exported file

### ISSUE THREAD

**Issue by chauchakching** [scottbedard/oc-debugbar-plugin#21]
The debugbar code is appended to exported file as well...
It should check the response output format before appending the debugbar code.

**Comment by abnerpsoares** [comment]
I have the same issue. Any solution?

**Comment by ghost** [comment]
On my **Plugin.php**, I've put this code inside the **public function boot()** method:

```
Event::listen('backend.page.beforeDisplay', function($controller, $action, $params){
       if( $action == 'download' ){
           \Debugbar::disable();
       }
});
```

**Comment by daftspunk** [comment]
Advise above looks good
