### ISSUE TITLE
Application::share() not found in OctoberCMS L5.5 (edge = true)

### ISSUE THREAD

**Issue by Verbat** [scottbedard/oc-debugbar-plugin#23]
When updating to the latest edge build the debug bar throws an exception.

Call to undefined method October\Rain\Foundation\Application::share()

C:\xampp\htdocs\www\plugins\bedard\debugbar\vendor\barryvdh\laravel-debugbar\src\ServiceProvider.php line 42

This is the affected line. 
$this->app['command.debugbar.clear'] = $this->app->share(
            function ($app) {
                return new Console\ClearCommand($app['debugbar']);
            }
        );

**Comment by scottbedard** [comment]
Thanks for the heads up, I've just upgraded to be compatible with 5.5!

https://github.com/scottbedard/oc-debugbar-plugin/commit/4fb0b661c2fe59a03c17712dd02b5bb1cb0f481a
