### ISSUE TITLE
Could you provide 1.0.8 release tag on git

### ISSUE THREAD

**Issue by tim0991** [scottbedard/oc-debugbar-plugin#24]
I installed your plugin with composer. 
when i update i got an error,  i found you upgrade it to laravel 5.5, but my application still at laravel 5.1

so i want to specify a tag like 
```json
"bedard/debugbar": "1.0.8"
```

but i only found `1.0.8` in version.yaml, if you provide the tag, it can be compatible with laravel5.1

**Comment by scottbedard** [comment]
No problem, I just tagged it! Let me know if it works for you.

**Comment by tim0991** [comment]
It works, thank you
