### ISSUE TITLE
Plugin is hidden on the marketplace

### ISSUE THREAD

**Issue by seanthepottingshed** [scottbedard/oc-debugbar-plugin#30]
@LukeTowers 

Plugin doesn't exist in Marketplace:

* https://octobercms.com/plugin/rainlab-debugbar 
* https://octobercms.com/plugin/bedard-debugbar - linked from here
* https://github.com/rainlab/debugbar-plugin - linked from here

**Comment by LukeTowers** [comment]
@daftspunk can you finish what you wanted on the plugin so that we can make it live?

**Comment by LukeTowers** [comment]
@seanthepottingshed in the meantime you can use composer to pull it in

**Comment by camohub** [comment]
The plugin is still not available in marketplace.

**Comment by daftspunk** [comment]
Please use composer to install this plugin. We may add it to the marketplace depending on its lifecycle moving forward
