### ISSUE TITLE
Debug bar is still enabled even if plugin is disabled

### ISSUE THREAD

**Issue by bennothommo** [scottbedard/oc-debugbar-plugin#34]
During debugging the error coming from #33, I realised that I had been operating the debug bar with the RainLab.Debugbar plugin disabled via the Backend.

This stems from the `barryvdh/laravel-debugbar` package being auto-discovered by Laravel - ostensibly, this means that our configuration is being overwritten by the package because their service provider is being loaded even when ours isn't.

The simple fix is to disable package discovery for this package, but I'm wondering if this will continue to occur with other plugins that have auto-discovered packages, as it's tying us to Laravel in a way that we have no control over with the plugin architecture. On the other hand, disabling package discovery entirely is going to probably cause mayhem with the plugins we have already.

For the sake of the argument, I had to add Dusk into the "don't discover" section on composer.json for our Laravel 6 upgrade and the RainLab.Dusk plugin. I don't think we can easily maintain this on a global scale.

**Comment by LukeTowers** [comment]
@bennothommo does the don't discover section get properly merged in from just the plugin's composer.json? Why do we need it in the project root and in the plugin?

**Comment by bennothommo** [comment]
@LukeTowers when I ran it with the Composer merge plugin, even with the "merge-extra" and "merge-extra-deep" options enabled, I couldn't get the Debug bar plugin to disallow discovery through the "extra" section - it would still discover the base package.

**Comment by bennothommo** [comment]
The only extra section that is correctly parsed seems to be the root `composer.json`.

**Comment by LukeTowers** [comment]
@bennothommo ah, it's because Laravel parses installed.json itself: 

https://github.com/laravel/framework/blob/9138b0b9e60df73e635f744085f0dae0a1c2f8ef/src/Illuminate/Foundation/PackageManifest.php#L133

We just need to override this in the October library, which is required anyways if we want to change its behaviour with a config value.

**Comment by bennothommo** [comment]
@LukeTowers I found another way:

https://github.com/laravel/framework/blob/9138b0b9e60df73e635f744085f0dae0a1c2f8ef/src/Illuminate/Foundation/Application.php#L601

We can copy over this block to our Application class and condition the highlighted line with a check for the config value - it allows the package discovery to still work, but just simply doesn't load the discovered packages.

**Comment by LukeTowers** [comment]
@bennothommo good idea. I'm not 100% sold on the config file disabling of it by default yet though, I'm sure it might affect @adrenth & other @vdlp devs since they're usually gung ho about Laravel features.

**Comment by adrenth** [comment]
We developed a `Vdlp.Developer` plugin which we use internally in our agency. This plugin is shipped with the `barryvdh/laravel-debugbar` package. This package publishes a config file `debugbar.php` to the project `config` folder.

> Also we require our own plugin `vdlp/oc-developer-plugin` in the `"require-dev"` section of `composer.json`. So it is never available on any testing/acceptance/production environment. It makes no sense by having debug packages/plugins installed there.

This default debugbar.php config file contains this line:
```
    /*
     |--------------------------------------------------------------------------
     | Debugbar Settings
     |--------------------------------------------------------------------------
     |
     | Debugbar is enabled by default, when debug is set to true in app.php.
     | You can override the value by setting enable to true or false instead of null.
...
'enabled' => env('DEBUGBAR_ENABLED', null),
```

So, it's enabled by default.

BUT...

All our projects have `.env` files by default and contain the `DEBUGBAR_ENABLED` environment variable. The only thin a developer needs to do is change this variable to enable or disable it:

```
DEBUGBAR_ENABLED = false|true
```

The intention of this plugin is having a debugbar in your project. So why disable it by default?

**Comment by LukeTowers** [comment]
@adrenth sorry for the confusion, we're talking about the Laravel package autodiscovery feature. We're considering disabling it by default in October and encouraging developers to manually load external packages' aliases and service providers from within their plugins instead so that we can properly prevent them from being loaded when the plugin (and thus the dependency) is present but disabled.

**Comment by bennothommo** [comment]
Resolved by https://github.com/octobercms/library/pull/492.
