### ISSUE TITLE
Error when saving data from backend

### ISSUE THREAD

**Issue by triasrahman** [scottbedard/oc-debugbar-plugin#35]
When saving data (create or update) from backend form, it always show an error like this.

![image](https://user-images.githubusercontent.com/7110859/83217548-3a176700-a196-11ea-8669-efafa2079fef.png)

```
[10:20:49] LOG.error: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Barryvdh\Debugbar\LaravelDebugbar::Barryvdh\Debugbar\{closure}(), 1 passed and exactly 2 expected in /Volumes/Data/Users/trias/Projects/octobercms/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php:377
Stack trace:
#0 [internal function]: Barryvdh\Debugbar\LaravelDebugbar->Barryvdh\Debugbar\{closure}(Object(October\Rain\Database\Connections\MySqlConnection))
#1 /Volumes/Data/Users/trias/Projects/octobercms/vendor/october/rain/src/Events/Dispatcher.php(233): call_user_func_array(Object(Closure), Array)
#2 /Volumes/Data/Users/trias/Projects/octobercms/vendor/october/rain/src/Events/Dispatcher.php(197): October\Rain\Events\Dispatcher->dispatch('connection.mysq...', Array, false)
#3 /Volumes/Data/Users/trias/Projects/octobercms/vendor/october/rain/src/Database/Connections/Connection.php(58): October\Rain\Events\Dispatcher->fire('connection.mysq...', Object(October\Rain\Database\Connections\MySqlConnection))
#4 /Volumes/Data/Users/trias/Projects/octobercms/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(96): October\Rain\Database\Connections\Connection->fireConnectionEvent('beganTransactio...')
#5 /Volumes/Data/Users/trias/Projects/octobercms/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(23): Illuminate\Database\Connection->beginTransaction()
#6 /Volumes/Data/Users/trias/Projects/octobercms/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(327): Illuminate\Database\Connection->transaction(Object(Closure))
#7 /Volumes/Data/Users/trias/Projects/octobercms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#8 /Volumes/Data/Users/trias/Projects/octobercms/modules/backend/Behaviors/FormController.php(255): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#9 [internal function]: Backend\Behaviors\FormController->create_onSave()
...
```

**Environment**
PHP 7.2.30
MySQL 5.5.5
OctoberCMS Build 465
Laravel 5.5.49

**Comment by LukeTowers** [comment]
This is because there is a required change to the October core that should have been applied for the 5.5 upgrade but was missed unfortunately, so it has instead been applied to the L6 upgrade. If you switch to the L6 branch then it should work fine. The L6 upgrade should come out as a stable update in a couple weeks after we've released 466 as a stable update.

**Comment by tobias-kuendig** [comment]
@daftspunk According to [the release page](https://github.com/rainlab/debugbar-plugin/releases/tag/v3.2.0), v3.2.0 should be compatible with October v1, but it seems like this issue is still present when the plugin is installed in an October v1 installation.

Is there any workaround for this?

**Comment by daftspunk** [comment]
Hey @tobias-kuendig We may need to update this advice. Try targeting v2.0 of this plugin to see if it helps.

**Comment by tobias-kuendig** [comment]
When using v2, the plugin does not load since it still uses the `Bedard` namespace. After changing it to `RainLab`, it does work. Could we get a v2 bugfix for this? I guess the easiest solution would be to have v2 compatible with October 1 and v3 with all newer versions.

Required changes:
https://github.com/rainlab/debugbar-plugin/compare/2.0.0...OFFLINE-GmbH:v2?expand=1

**Comment by tobias-kuendig** [comment]
Scratch that! I just had to install the `bedard/debugbar` package instead of `rainlab/debugbar-plugin` to get v2 running.

```
composer require bedard/debugbar ^2.0
```
