### ISSUE TITLE
v3.1.0 does't work

### ISSUE THREAD

**Issue by Metallizzer** [scottbedard/oc-debugbar-plugin#36]
Hi.
Just installed new version on fresh installed cms. And got an error
```
Illegal offset type in isset or empty" on line 280 of 
/vendor/october/rain/src/Events/Dispatcher.php
```

**October cms build 465**
**PHP 7.4.5**

Disabling config debugbar.collectors.events seems work

**Comment by bennothommo** [comment]
@Metallizzer this plugin is targeting Laravel 6 at this point, so you will need to use the `wip/laravel-6` branch of October CMS to be able to use the plugin to its full potential. You can also downgrade the plugin by removing it from your project and downloading [version 3.0.1](https://github.com/rainlab/debugbar-plugin/releases/tag/3.0.1) of the plugin, but ensure that you only download this on a development copy of October CMS, as there's a security fix in 3.1.0 that you will be missing out on.

**Comment by Metallizzer** [comment]
@bennothommo thanks for answer. 
As i said before, i disabled config debugbar.collectors.events and plugin seems work as expected. 
Previous version had this settings to false. https://github.com/rainlab/debugbar-plugin/commit/86dd29f9866d712de7d98f5f9dc67751b82ecd18#diff-215adb4f17e6c57786bec362c538ccb8L120

**Comment by LukeTowers** [comment]
Good to hear @Metallizzer. I would normally release an update disabling it by default again, but we're going to be releasing the L6 upgrade in a couple weeks so I don't think I'll bother with that.

**Comment by Rike-cz** [comment]
I had the same problem as @Metallizzer, so I downgraded to 3.0.1 and now AJAX requests fail with `"Type error: Too few arguments to function Barryvdh\Debugbar\LaravelDebugbar::Barryvdh\Debugbar\{closure}(), 1 passed and exactly 2 expected" on line 377 of C:\...\vendor\barryvdh\laravel-debugbar\src\LaravelDebugbar.php`
Is there plan to improve 3.0.1 or is deprecated?

**Comment by LukeTowers** [comment]
@Rike-cz no, we don't ever support old versions of plugins / core since it's an evergreen release cycle. Your problem is because of a change in the base library, can you paste what's on line 377? Also are you using composer or the marketplace?

**Comment by Rike-cz** [comment]
I am using composer as default. As far as I know, there is no possibility to install older version through marketplace. But update to 3.1 version was made via marketplace and rollbacked via composer.
```
$db->getEventDispatcher()->listen(
    'connection.*.beganTransaction',
    function ($event, $params) use ($queryCollector) { <----- this line is 377
        $queryCollector->collectTransactionEvent('Begin Transaction', $params[0]);
    }
);
```

**Comment by LukeTowers** [comment]
Solution should be simple, the change that breaks it on the develop branch of october was https://github.com/barryvdh/laravel-debugbar/commit/31bb601e1157b9a7333cfa88ea19daddbabd9942.

Just add `"barryvdh/laravel-debugbar": "3.2.9"` to your project's composer.json file and it should work even on 3.1.0 of this plugin (as long as you also disable the events collector).

**Comment by daslicht** [comment]
@LukeTowers is the Laravel6 branch fully working or are there still downsides?, please 

[edit]
just installed october from the laravel 6 branch via cli
and then: ```composer require rainlab/debugbar-plugin```
result 500

**Comment by LukeTowers** [comment]
@daslicht what's the error?

**Comment by daslicht** [comment]
I dont remember but i can reproduce it later if needed

**Comment by LukeTowers** [comment]
If you could do that I would appreciate that. We would prefer to fix any issues that come up now before we launch L6
