### ISSUE TITLE
500 Server Error after install ?

### ISSUE THREAD

**Issue by daslicht** [scottbedard/oc-debugbar-plugin#37]
Hi,
i installed the debugbar to my project, while installing I got an error.
I tried refreshing teh page now I just get 500 server error?

I have noticed teh the file:
storage/framework/classes is malformed, teh arry was no longer closed

Is there a known solution for this please?

**Comment by daslicht** [comment]
looks like it has nothing to do with debug but and it is indeed a server problem *eyesroll*

**Comment by daslicht** [comment]
edit server is working properly

**Comment by daslicht** [comment]
Ok, I just installed OctoberCMS from ground up.
After the installation was complete I logged into teh backend and installed debugbar.
I got the same error as in my previous installation:
![](https://i.imgur.com/hYL0BX9.png)
any idea ?


When I press try again I get an infinite:
![](https://i.imgur.com/SnmtQjh.png)

When I open the page now in a new tab I just get internal server error 500 again.

Deleting ```plugins/rainlab/debugbar``` makes october  accesible again

**Comment by RomainMazB** [comment]
See this maintainer's comment: https://github.com/rainlab/debugbar-plugin/issues/36#issuecomment-636872790 , I was facing the same problem, install the 3.0.1 and it should be ok.

**Comment by daslicht** [comment]
What a mess, something like this should not happen when you isntall form the Market !

**Comment by RomainMazB** [comment]
I just can agree on this ;) .

There must be a good reason for this though

**Comment by LukeTowers** [comment]
We've hidden this plugin from the marketplace because it's targeting the L6 upgrade which isn't released yet.

**Comment by daslicht** [comment]
I trid it on a virgin l6 installation, it also breaks it

**Comment by LukeTowers** [comment]
@daslicht what's the error specifically? Sounds more like a broken installation.

**Comment by RomainMazB** [comment]
> We've hidden this plugin from the marketplace because it's targeting the L6 upgrade which isn't released yet.

@LukeTowers It's a good thing, but didn't you have the possibility to just block the installed default version from the marketplace the same way you've already done with [Static Pages](https://octobercms.com/plugin/rainlab-translate#changelog) or [Translate](https://octobercms.com/plugin/rainlab-translate#changelog)?

I'm just curious: I've discovered few weeks ago this "pending" status on plugins and don't understand the reason why it's not feasible with the DebugBar?

**Comment by LukeTowers** [comment]
@RomainMazB it is feasible, it's just not able to be applied retroactively (without manual intervention). Plus we don't want people using the older versions anyways so we're just going to hide it for now. The L6 build should be out shortly.

**Comment by daslicht** [comment]
> @daslicht what's the error specifically? Sounds more like a broken installation.
nope, I can reproduce it 100% like this:


**Install October wip/laravel-6**
```
php -r "eval('?>'.file_get_contents('https://octobercms.com/api/installer'));"
php artisan october:install
2 SQLite
installation works 
```

**Install composer**
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

bash-4.4$ php composer.phar require rainlab/debugbar-plugin
Using version ^3.1 for rainlab/debugbar-plugin
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 1 removal
  - Removing wikimedia/composer-merge-plugin (dev-master 73e4ed4)
  - Installing maximebf/debugbar (v1.16.3): Loading from cache
  - Installing barryvdh/laravel-debugbar (v3.3.3): Loading from cache
  - Installing rainlab/debugbar-plugin (3.1.0): Loading from cache
maximebf/debugbar suggests installing predis/predis (Redis storage)
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package leafo/scssphp is abandoned, you should avoid using it. Use scssphp/scssphp instead.
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Writing lock file
Generating autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
bash-4.4$

result SERVER ERROR 500
```

**Comment by LukeTowers** [comment]
That is 100% a broken installation. The installer package installs the latest stable build (465) AFAIK, not the Laravel 6 version. Install via composer with `composer create-project octobercms/october` and then follow the upgrade guide steps here to get a working L6 build: https://github.com/octoberrain/meta/blob/master/l6-upgrade-notes.md

You can even see in your composer output that it's manually creating a brand new composer.json file since one doesn't exist (since you're installing the consumer version, not the developer version)

**Comment by daslicht** [comment]
ahh ok i thought the docu is updated for the branch either
