### ISSUE TITLE
The plugin is hidden and cannot be installed  - via artisan plugin:install

### ISSUE THREAD

**Issue by danielbidala** [scottbedard/oc-debugbar-plugin#40]
I get the following error when I try to install the plugin via artisan plugin:install.

> The plugin is hidden and cannot be installed

October cms 1.1.*

Any idea why?

**Comment by LukeTowers** [comment]
Yes, because it's currently hidden on the marketplace until the marketplace has been updated to support 1.1 as this plugin requires v1.1 of October. Use composer to install instead for now.

**Comment by danielbidala** [comment]
Thanks @LukeTowers I've installed it with `composer require rainlab/debugbar-plugin` and than ran `php artisan plugin:refresh Rainlab.Debugbar` to see the plugin in the backend Settings/Updates&Plugins page.

**Comment by LukeTowers** [comment]
Note that you can also just run `php artisan october:up` when installing a plugin via composer as that will run any pending migrations which would include that plugin's migrations.
