### ISSUE TITLE
Improve quality of event performance tracking

### ISSUE THREAD

**Issue by LukeTowers** [scottbedard/oc-debugbar-plugin#42]
Right now performance / timing tracking on events uses the difference between when the last event was fired to when the current event was fired to say how long a given event took to process. This is obviously wildly inaccurate and unhelpful, so it would be better if we could instead implement our own event data collector that actually tracked how long a given event was taking to execute by hooking one wildcard listener as the highest priority listener (with PHP_INT_MAX) and another wildcard listener as the lowest priority listener (with PHP_INT_MIN) and then recording the timing difference between those two listeners being fired.

This would require a change being made to the October core as currently wildcard listeners don't support subscribing to events with priority, and even if they did you'd still have to ensure that they were added to the priority stream of the non-wildcard listeners correctly.

Something roughly like the following:
```php
$events->listen('*', [$this, 'onWildcardEventStart'], PHP_INT_MAX);
        $events->listen('*', [$this, 'onWildcardEventEnd'], PHP_INT_MIN);
    }

    protected $timings = [];
    public function onWildCardEventStart($name = null, $data = [])
    {
        if (empty($name)) { return; }
        $this->timings[$name] = microtime(true);
    }
    public function onWildCardEventEnd($name = null, $data = [])
    {
        if (empty($name)) { return; }
        $this->addMeasure($name, $this->timings[$name], microtime(true), $this->prepareParams($data));
    }
```

**Comment by LukeTowers** [comment]
Would be nice if we could just make a PR to the debugbar repo for this, but unfortunately I believe the Laravel event system removed the concept of event priority a while ago.

**Comment by LukeTowers** [comment]
@bennothommo any thoughts on the above?

**Comment by bennothommo** [comment]
I think it's a great idea. There is a potential library we could use to avoid having to put in priority for wildcard events: https://github.com/goaop/framework. That library allows us to hook into method calls and invocations, and define advices before and after calls - so theoretically, we could watch for any `dispatch` calls in the Dispatcher, and add some advices/callbacks through the Debugbar plugin. This could also be useful in other ways - ie. logging slow method calls, for auditing, etc.

Only issue is that the library needs to be loaded pretty early in the piece - not sure if a Plugin initialisation is going to be early enough.

**Comment by daftspunk** [comment]
Yes. The concept of priority is gone in Laravel when they changed the concept of Events entirely. Bit of a bummer
