### ISSUE TITLE
Composer install crash the whole application

### ISSUE THREAD

**Issue by camohub** [scottbedard/oc-debugbar-plugin#45]
- OctoberCMS Build: v2.0.7
- DebugBar Plugin Version: v3.1.1
- PHP Version: 7.4

### Description:

As I install this plugin via composer require rainlab/debugbar-plugin the application throws me an error I mean localhost refuse me the access. 

![Screenshot (388)](https://user-images.githubusercontent.com/8393426/115253711-ee163d80-a12c-11eb-852d-53fba0d8c811.png)

### Steps To Reproduce:

Install the latest version of October cms and latest version of plugin.

**Comment by daftspunk** [comment]
Updating to `october/rain:2.0.2` should fix this

Thanks

**Comment by camohub** [comment]
I try Composer installation again. Now it  does not crash and I can see the plugin in the code. 
But I dont see any debug bar. I am logged in, I am superuser, config/app.php debug is TRUE. What else sould I do?
