### ISSUE TITLE
New Collectors

### ISSUE THREAD

**Issue by barryvdh** [scottbedard/oc-debugbar-plugin#48]
Hey, 
I've started using OctoberCMS for a client (existing project) and I've installed Debugbar (obviously). Some things maybe we can work together on:

 - I see @tomaszstrojny added a new Collector for Models already, so that is nice.
 - Views don't seem to get displayed, but we could use the `cms.page.renderContent` and `cms.page.renderPartial` perhaps, to at least show the name?
 - Maybe we can show some CMS information using the `cms.page.display` event (eg layout etc)

The controller doesn't give me much useful information though, mostly `Cms\Classes\CmsController@run`

I'll see if I can make some prototype, but if there is anything you need from me to change upstream to make it easier to extend, just let me know!

**Comment by barryvdh** [comment]
What I'm thinking of is extending the LaravelDebugbar to OctoberDebugbar + making sure each collector is added it in its own method, so we can just override the base LaravelDebugbar and add/swap out some collectors (like views etc)

**Comment by daftspunk** [comment]
All sounds good, likewise, let us know if there are any core changes needed along the way.

**Comment by barryvdh** [comment]
I added the basics for CMS/Backend routes in #49 and Twig in #50 :)

**Comment by daftspunk** [comment]
User testing seems to be positive. Ready to release?

**Comment by barryvdh** [comment]
Guess so. Could probably enhance the components tab a bit but maybe just let them try it out first.

**Comment by daftspunk** [comment]
Alright, added some extra component details in c692d4e5ff50513372fbce98ff1a17775b024938. Wish there was a widget for showing a nested variable list, the inspector mode is good enough for now.

**Comment by daftspunk** [comment]
Shipped these enhancements as v3.3.0.

Thanks for this, you rock!
