### ISSUE TITLE
OctoberModelsCollector causes models not able to being serialized

### ISSUE THREAD

**Issue by adrenth** [scottbedard/oc-debugbar-plugin#56]
- OctoberCMS Build: latest
- DebugBar Plugin Version: 3.3.1
- PHP Version: 7.4

### Description:

With the DebugBar enabled it is not possible to serialize models. Models are being serialized when you are using them as payload in a job. The trait SerializesModels is trying to serialize the model, but that will result in a "Serialization of 'Closure' is not allowed" exception.

### Steps To Reproduce:

Create a model:

```
use October\Rain\Database\Model;

class MyTestModel extends Model
{
    protected $table = 'my_table';
}
```

And (with the DebugBar enabled):

```
$myTestModel = new MyTestModel();

dd(serialize($myTestModel));
```

----

The `OctoberModelsCollector` does nothing special, but it does bind an event to the model for which there's no way to disable it through configuration option (see `config.collectors.models`). The only way is to uninstall the DebugBar plugin completely to prevent the OctoberModelsCollector to be initialized.

```
  #emitterEventCollection: array:1 [
    "model.afterFetch" => array:1 [
      0 => array:1 [
        0 => Closure() {#1941
          class: "RainLab\Debugbar\DataCollectors\OctoberModelsCollector"
          this: RainLab\Debugbar\DataCollectors\OctoberModelsCollector {#1022 …}
          use: {
            $model: Nip\Person\Models\MyTestModel {#1908}
          }
        }
      ]
    ]
  ]
```

In my opinion the collectors should be enabled/disabled by configuration:

In the `boot()` method of the Plugin.php the collectors are always added:

```
        if (App::runningInBackend()) {
            $this->addBackendCollectors();
        }
        else {
            $this->registerCmsTwigExtensions();
            $this->addFrontendCollectors();
        }

        $this->addGlobalCollectors();
```

If the Debugbar is disabled; it should not boot and add collectors.

Maybe add this line to the top of the boot() method:

```
    public function boot()
    {
        // Configure the debugbar
        Config::set('debugbar', Config::get('rainlab.debugbar::config'));

        if (Config::get('debugbar.enabled') === false) {
            return;
        }
   ...
```

**Comment by daftspunk** [comment]
Makes sense, thanks!
