### ISSUE TITLE
Uncaught TypeError: url.indexOf is not a function

### ISSUE THREAD

**Issue by dariopetraroia** [scottbedard/oc-debugbar-plugin#57]
- OctoberCMS Build: 2.1.28
- DebugBar Plugin Version: 3.3.2
- PHP Version: 8.0

### Description:

Uncaught TypeError: url.indexOf is not a function
    at XMLHttpRequest.<anonymous> (javascript?v=1640110810:1210:52)

(anonymous) @ javascript?v=1640110810:1210
XMLHttpRequest.send (async)
submitRequest @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:2781
_uploadData @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:2505
(anonymous) @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:2369
(anonymous) @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:2523
transformFile @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:677
_loop @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:2520
_transformFiles @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:2529
uploadFiles @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:2281
processFiles @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:2186
processFile @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:2154
processQueue @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:2143
(anonymous) @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:1880
setTimeout (async)
enqueueFile @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:1879
(anonymous) @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:1841
accept @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:532
accept @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:1807
addFile @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:1834
(anonymous) @ f2479d67261519cb76d3bc7fa8bd46b4-1618559674:1246

if (xhr.readyState == 4 && url.indexOf(skipUrl) !== 0) {

### Steps To Reproduce:

Upload File using Responisve Uploader
https://github.com/responsiv/uploader-plugin

**Comment by daftspunk** [comment]
Hi Dario,

This is fixed in the uploader plugin. Please update it to v1.0.6

Thanks
