### ISSUE TITLE
Twig "debug" functionality broken

### ISSUE THREAD

**Issue by lieszkol** [scottbedard/oc-debugbar-plugin#58]
- OctoberCMS Build: 2.2.33
- DebugBar Plugin Version: 3.3.3
- PHP Version: 7.x irrelevant

### Description:

You've disabled twig functions in [279609efa38e2e62f22f75cca20d24191c1cabfb](https://github.com/rainlab/debugbar-plugin/commit/279609efa38e2e62f22f75cca20d24191c1cabfb), which causes any pages using the twig "debug" function to fail with "Unknown "debug" function. Did you mean "date", "dump", "random", "include", "redirect", "placeholder"?"

A fix is to edit composer.json to fix the plugin version to 3.2:

```
"rainlab/debugbar-plugin": "3.2"
```

and then running 

```
composer update
php artisan october:migrate
```

However this is hardly obvious and took me 2 hours to figure out. Other devs can run into the same. Please consider adding a note to explain this to README.md to save other devs the hassle until whatever the issue is that lead you to disable twig functionality is resolved?

### Steps To Reproduce:

Add the current version of the plugin to a project:

```
composer require rainlab/debugbar-plugin
```

or upgrade an existing project:

```
composer update
```

**Comment by daftspunk** [comment]
Hey @lieszkol 

Apologies for the frustration here. We anticipated this to be fixed rather quickly, instead, it has taken a bit longer than expected.

We will keep the Twig support around for v2 (43679d96a702ed52082015424009d4788db005d4), hopefully, it helps.

**Comment by lieszkol** [comment]
Thanks daftspunk!!! And thank you for the plugin.
