### ISSUE TITLE
Debugbar working only on chrome browser

### ISSUE THREAD

**Issue by jjezik82** [scottbedard/oc-debugbar-plugin#61]
Hi there, I noticed that debugbar is only working on chrome browser. I was trying out firefox the other day, but I couldn't make it work. Also on chrome in incognito mode...since then I tried a few other browsers, but debugbar only showed on chrome. It's always the same project, and there's debug set to true in .env . So far I didn't find any answer on why it only shows on chrome, if I'm missing something in my settings? Is it only me, or is this happening to oher people too? Thanks for answers.

**Comment by rubenvanerk** [comment]
I think the bar only shows up when you're logged in in the backend. Are you logged in in the other browsers you tested with?

**Comment by jjezik82** [comment]
You're absolutely right, I never noticed this. Thanks for the answer.
